"""added content_type to table cached_content

Revision ID: 422e338d5b75
Revises: c2966f1ff0f9
Create Date: 2026-03-04 17:06:26.828906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422e338d5b75'
down_revision: Union[str, Sequence[str], None] = 'c2966f1ff0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_content', sa.Column('content_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cached_content', 'content_type')
    # ### end Alembic commands ###
