"""added table content_files which relates to cached_content

Revision ID: 93f26ff53358
Revises: 422e338d5b75
Create Date: 2026-03-04 18:15:40.725041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f26ff53358'
down_revision: Union[str, Sequence[str], None] = '422e338d5b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['cached_content.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cached_content', 'content_type')
    op.drop_column('cached_content', 'name')
    op.drop_column('cached_content', 'telegram_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cached_content', sa.Column('telegram_file_id', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('cached_content', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('cached_content', sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_table('content_files')
    # ### end Alembic commands ###
