"""change content_type to is_video in content_file table

Revision ID: ab2626013b3b
Revises: 93f26ff53358
Create Date: 2026-03-04 20:59:10.452343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2626013b3b'
down_revision: Union[str, Sequence[str], None] = '93f26ff53358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_files', sa.Column('is_video', sa.Boolean(), nullable=False))
    op.drop_column('content_files', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_files', sa.Column('content_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('content_files', 'is_video')
    # ### end Alembic commands ###
